// This file is generated by Velite

import type __vc from '../velite.config.ts'

type Collections = typeof __vc.collections

export type Note = Collections['notes']['schema']['_output']
export declare const notes: Note[]
